spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user01
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
    google:
      genai:
        api-key: AIzaSyD-7YXzCzcAIP-ZLW1K3kvezJGwQKAZvQk
        chat:
          options:
            model: gemini-2.5-flash
        embedding:
          api-key: AIzaSyD-7YXzCzcAIP-ZLW1K3kvezJGwQKAZvQk
          options:
            model: text-embedding-004
    vectorstore:
      pgvector:
        initialize-schema: false
        dimensions: 768

jwt:
  secret: mysecret

logging:
  level:
    root: INFO
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG