spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user01
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    repair-on-migrate: true
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
    google:
      genai:
        api-key: AIzaSyCk0APo6MPj964UionbjqMi2h5ChPLdMbw
        project-id: gen-lang-client-0176409509
        location: us-central1
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7
        embedding:
          api-key: AIzaSyCk0APo6MPj964UionbjqMi2h5ChPLdMbw
          options:
            model: text-embedding-004
    vectorstore:
      pgvector:
        initialize-schema: false
        dimensions: 768
        distance-type: cosine_distance
s3:
  access-key: AKIAIOSFODNN7EXAMPLE
  secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  region: ap-northeast-2
  bucket: my-app-bucket
ai:
  server:
    base-url: http://52.55.50.125:8000
    token: 1ae47ae448e734ac74affae0bc0b5f402f1d1c4ae1b52cd5beceb5a92b57a7d5

oauth:
  google:
    client-id: "481500254244-t5ram70598u3m967nmnv3a4o2j0toati.apps.googleusercontent.com"

jwt:
  secret: G8gAOJ1j3Gw+wL5ewdF5Qem27CL3+tJL2K6qYL72pfkBXJSIixiUmm3BhFppxSV0XrU9v6iYUGmyJ40hxnE6w==
  access-expiration-minutes: 30
  refresh-expiration-days: 14

logging:
  level:
    root: INFO
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG