-- FCM device token registry for push notifications.
-- One row per (user, device-installed token). Token values are globally unique
-- because reinstalling on a new account moves the token to a new user.

CREATE TABLE user_fcm_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_value VARCHAR(512) NOT NULL,
    device_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_user_fcm_token_value_not_blank
        CHECK (btrim(token_value) <> ''),
    CONSTRAINT ck_user_fcm_token_device_type
        CHECK (device_type IN ('ANDROID', 'IOS', 'WEB')),
    CONSTRAINT uk_user_fcm_token_token_value
        UNIQUE (token_value),
    CONSTRAINT fk_user_fcm_token_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_fcm_token_user_id
    ON user_fcm_token (user_id);
