-- In-app alarm history. Each row represents a single notification delivered to a user.
-- Mapped to com.example.freshkitchen.domain.alarm.entity.Alarm.

CREATE TABLE alarm (
    alarm_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    alarm_date_time TIMESTAMP NULL,
    title VARCHAR(255) NULL,
    content VARCHAR(255) NULL,
    url VARCHAR(255) NULL,
    img VARCHAR(255) NULL,
    CONSTRAINT fk_alarm_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_alarm_user_id ON alarm (user_id);