-- Inquiry history table. Stores user inquiries/reports with optional admin replies.

CREATE TABLE inquiry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT          NOT NULL,
    type        VARCHAR(20)     NOT NULL,
    category    VARCHAR(20)     NOT NULL,
    content     TEXT            NOT NULL,
    image_url   VARCHAR(1024),
    status      VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    admin_reply TEXT,
    answered_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_inquiry_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_inquiry_type
        CHECK (type IN ('INQUIRY', 'REPORT')),
    CONSTRAINT ck_inquiry_category
        CHECK (category IN ('RECIPE', 'AI', 'OTHER')),
    CONSTRAINT ck_inquiry_status
        CHECK (status IN ('PENDING', 'ANSWERED')),
    CONSTRAINT ck_inquiry_answered_consistency
        CHECK (
            (status = 'ANSWERED' AND admin_reply IS NOT NULL AND answered_at IS NOT NULL)
            OR
            (status = 'PENDING' AND admin_reply IS NULL AND answered_at IS NULL)
        )
);

CREATE INDEX idx_inquiry_user_id ON inquiry (user_id);
CREATE INDEX idx_inquiry_status  ON inquiry (status);
