-- Fresh-Kitchen V1 schema
-- PostgreSQL 16+
-- Notes:
-- 1. `users` is used instead of `user` because `user` is reserved in PostgreSQL.
-- 2. V1 scope is limited to user/profile/storage/ingredient/catalog/image domains.
-- 3. Basic storage bootstrap (FRIDGE/FREEZER/PANTRY) is created by application logic, not by the database.
-- 4. An ingredient may have multiple images, and if any exist exactly one must be marked as primary.
-- 5. Mutable aggregate roots include a `version` column for JPA optimistic locking.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_user_id VARCHAR(255) NOT NULL,
    provider VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    inactive_at TIMESTAMPTZ NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_provider_user_id_not_blank
        CHECK (btrim(provider_user_id) <> ''),
    CONSTRAINT ck_users_provider
        CHECK (provider IN ('GOOGLE', 'KAKAO')),
    CONSTRAINT ck_users_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_users_status_inactive_at_consistency
        CHECK (
            (status = 'ACTIVE' AND inactive_at IS NULL)
            OR (status = 'INACTIVE' AND inactive_at IS NOT NULL)
        ),
    CONSTRAINT uk_users_provider_provider_user_id
        UNIQUE (provider, provider_user_id)
);

CREATE TABLE user_profile (
    user_id BIGINT PRIMARY KEY,
    nickname VARCHAR(100) NOT NULL,
    profile_image_url TEXT NULL,
    bio TEXT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_user_profile_nickname_not_blank
        CHECK (btrim(nickname) <> ''),
    CONSTRAINT fk_user_profile_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_profile_preferred_ingredient (
    user_id BIGINT NOT NULL,
    ingredient_name VARCHAR(100) NOT NULL,
    PRIMARY KEY (user_id, ingredient_name),
    CONSTRAINT ck_user_profile_preferred_ingredient_name_not_blank
        CHECK (btrim(ingredient_name) <> ''),
    CONSTRAINT fk_user_profile_preferred_ingredient_user
        FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
);

CREATE TABLE user_profile_food_style (
    user_id BIGINT NOT NULL,
    food_style VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, food_style),
    CONSTRAINT ck_user_profile_food_style_not_blank
        CHECK (btrim(food_style) <> ''),
    CONSTRAINT fk_user_profile_food_style_user
        FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
);

CREATE TABLE user_profile_allergy (
    user_id BIGINT NOT NULL,
    allergy_type VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, allergy_type),
    CONSTRAINT ck_user_profile_allergy_type_not_blank
        CHECK (btrim(allergy_type) <> ''),
    CONSTRAINT fk_user_profile_allergy_user
        FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
);

CREATE TABLE user_profile_cooking_tool (
    user_id BIGINT NOT NULL,
    cooking_tool VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, cooking_tool),
    CONSTRAINT ck_user_profile_cooking_tool_not_blank
        CHECK (btrim(cooking_tool) <> ''),
    CONSTRAINT fk_user_profile_cooking_tool_user
        FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON DELETE CASCADE
);

CREATE TABLE storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    storage_type VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_storage_type
        CHECK (storage_type IN ('FRIDGE', 'FREEZER', 'PANTRY')),
    CONSTRAINT ck_storage_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT fk_storage_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_storage_user_storage_type
        UNIQUE (user_id, storage_type),
    CONSTRAINT uk_storage_id_user
        UNIQUE (id, user_id)
);

CREATE TABLE image_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    asset_type VARCHAR(30) NOT NULL,
    kind VARCHAR(30) NOT NULL,
    storage_provider VARCHAR(20) NOT NULL,
    image_url TEXT NOT NULL,
    width INT NULL,
    height INT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_image_asset_asset_type
        CHECK (asset_type IN ('USER_UPLOAD', 'SYSTEM_DEFAULT')),
    CONSTRAINT ck_image_asset_kind
        CHECK (kind = 'INGREDIENT'),
    CONSTRAINT ck_image_asset_storage_provider
        CHECK (storage_provider IN ('LOCAL', 'S3')),
    CONSTRAINT ck_image_asset_image_url_not_blank
        CHECK (btrim(image_url) <> ''),
    CONSTRAINT ck_image_asset_width_positive
        CHECK (width IS NULL OR width > 0),
    CONSTRAINT ck_image_asset_height_positive
        CHECK (height IS NULL OR height > 0),
    CONSTRAINT ck_image_asset_owner_consistency
        CHECK (
            (asset_type = 'SYSTEM_DEFAULT' AND user_id IS NULL)
            OR (asset_type = 'USER_UPLOAD' AND user_id IS NOT NULL)
        ),
    CONSTRAINT fk_image_asset_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE ingredient_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    default_image_asset_id BIGINT NULL,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(30) NOT NULL,
    default_storage_type VARCHAR(20) NOT NULL,
    icon_url TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ingredient_catalog_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT ck_ingredient_catalog_category
        CHECK (category IN ('VEGETABLE', 'FRUIT', 'MEAT', 'SEAFOOD', 'DAIRY', 'SAUCE', 'DRINK', 'ETC')),
    CONSTRAINT ck_ingredient_catalog_default_storage_type
        CHECK (default_storage_type IN ('FRIDGE', 'FREEZER', 'PANTRY')),
    CONSTRAINT fk_ingredient_catalog_default_image
        FOREIGN KEY (default_image_asset_id) REFERENCES image_asset(id) ON DELETE SET NULL,
    CONSTRAINT uk_ingredient_catalog_name
        UNIQUE (name)
);

CREATE TABLE category_expiry_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(30) NOT NULL,
    storage_type VARCHAR(20) NOT NULL,
    shelf_life_days INT NOT NULL,
    reference_note TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_category_expiry_rule_category
        CHECK (category IN ('VEGETABLE', 'FRUIT', 'MEAT', 'SEAFOOD', 'DAIRY', 'SAUCE', 'DRINK', 'ETC')),
    CONSTRAINT ck_category_expiry_rule_storage_type
        CHECK (storage_type IN ('FRIDGE', 'FREEZER', 'PANTRY')),
    CONSTRAINT ck_category_expiry_rule_shelf_life_days
        CHECK (shelf_life_days >= 0),
    CONSTRAINT uk_category_expiry_rule_category_storage_type
        UNIQUE (category, storage_type)
);

CREATE TABLE catalog_expiry_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_id BIGINT NOT NULL,
    storage_type VARCHAR(20) NOT NULL,
    shelf_life_days INT NOT NULL,
    reference_note TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_catalog_expiry_rule_storage_type
        CHECK (storage_type IN ('FRIDGE', 'FREEZER', 'PANTRY')),
    CONSTRAINT ck_catalog_expiry_rule_shelf_life_days
        CHECK (shelf_life_days >= 0),
    CONSTRAINT fk_catalog_expiry_rule_catalog
        FOREIGN KEY (catalog_id) REFERENCES ingredient_catalog(id) ON DELETE CASCADE,
    CONSTRAINT uk_catalog_expiry_rule_catalog_storage_type
        UNIQUE (catalog_id, storage_type)
);

CREATE TABLE ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    storage_id BIGINT NOT NULL,
    catalog_id BIGINT NULL,
    name VARCHAR(100) NOT NULL,
    registered_at DATE NULL,
    expires_at DATE NULL,
    expiry_source_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    consumed_at DATE NULL,
    discarded_at DATE NULL,
    note TEXT NULL,
    source_type VARCHAR(20) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ingredient_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT ck_ingredient_expiry_source_type
        CHECK (expiry_source_type IN ('MANUAL', 'POLICY', 'OCR', 'UNKNOWN')),
    CONSTRAINT ck_ingredient_status
        CHECK (status IN ('ACTIVE', 'CONSUMED', 'DISCARDED')),
    CONSTRAINT ck_ingredient_source_type
        CHECK (source_type IN ('MANUAL', 'PHOTO', 'RECEIPT')),
    CONSTRAINT ck_ingredient_expires_at_after_registered_at
        CHECK (
            registered_at IS NULL
            OR expires_at IS NULL
            OR expires_at >= registered_at
        ),
    CONSTRAINT ck_ingredient_status_dates_consistency
        CHECK (
            (status = 'ACTIVE' AND consumed_at IS NULL AND discarded_at IS NULL)
            OR (status = 'CONSUMED' AND consumed_at IS NOT NULL AND discarded_at IS NULL)
            OR (status = 'DISCARDED' AND discarded_at IS NOT NULL AND consumed_at IS NULL)
        ),
    CONSTRAINT fk_ingredient_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ingredient_storage_owner
        FOREIGN KEY (storage_id, user_id) REFERENCES storage(id, user_id) ON DELETE CASCADE,
    CONSTRAINT fk_ingredient_catalog
        FOREIGN KEY (catalog_id) REFERENCES ingredient_catalog(id) ON DELETE SET NULL
);

CREATE TABLE image_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_asset_id BIGINT NOT NULL,
    variant_type VARCHAR(20) NOT NULL,
    image_url TEXT NOT NULL,
    width INT NOT NULL,
    height INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_image_variant_variant_type
        CHECK (variant_type IN ('THUMBNAIL', 'DETAIL')),
    CONSTRAINT ck_image_variant_image_url_not_blank
        CHECK (btrim(image_url) <> ''),
    CONSTRAINT ck_image_variant_width_positive
        CHECK (width > 0),
    CONSTRAINT ck_image_variant_height_positive
        CHECK (height > 0),
    CONSTRAINT fk_image_variant_asset
        FOREIGN KEY (image_asset_id) REFERENCES image_asset(id) ON DELETE CASCADE,
    CONSTRAINT uk_image_variant_asset_variant_type
        UNIQUE (image_asset_id, variant_type)
);

CREATE TABLE ingredient_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL,
    image_asset_id BIGINT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    source_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ingredient_image_source_type
        CHECK (source_type IN ('PHOTO', 'DEFAULT')),
    CONSTRAINT fk_ingredient_image_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredient(id) ON DELETE CASCADE,
    CONSTRAINT fk_ingredient_image_asset
        FOREIGN KEY (image_asset_id) REFERENCES image_asset(id) ON DELETE RESTRICT,
    CONSTRAINT uk_ingredient_image_ingredient_asset
        UNIQUE (ingredient_id, image_asset_id)
);

CREATE OR REPLACE FUNCTION enforce_ingredient_image_primary_invariant()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    target_ingredient_id BIGINT;
    image_count BIGINT;
    primary_count BIGINT;
BEGIN
    target_ingredient_id := COALESCE(NEW.ingredient_id, OLD.ingredient_id);

    SELECT COUNT(*), COUNT(*) FILTER (WHERE is_primary = TRUE)
      INTO image_count, primary_count
      FROM ingredient_image
     WHERE ingredient_id = target_ingredient_id;

    IF image_count > 0 AND primary_count <> 1 THEN
        RAISE EXCEPTION 'ingredient % must have exactly one primary image', target_ingredient_id;
    END IF;

    RETURN NULL;
END;
$$;

CREATE INDEX idx_ingredient_user_status_expires_at
    ON ingredient (user_id, status, expires_at);

CREATE INDEX idx_ingredient_storage_id_status
    ON ingredient (storage_id, status);

CREATE INDEX idx_ingredient_catalog_id
    ON ingredient (catalog_id);

CREATE UNIQUE INDEX uk_ingredient_image_primary
    ON ingredient_image (ingredient_id)
    WHERE is_primary = TRUE;

CREATE CONSTRAINT TRIGGER ck_ingredient_image_exactly_one_primary
    AFTER INSERT OR UPDATE OR DELETE ON ingredient_image
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION enforce_ingredient_image_primary_invariant();

CREATE INDEX idx_ingredient_image_asset_id
    ON ingredient_image (image_asset_id);
