CREATE EXTENSION IF NOT EXISTS vector;

DROP TABLE IF EXISTS chat_pgvector CASCADE;
CREATE TABLE IF NOT EXISTS public.chat_pgvector (
                                                    id VARCHAR(255) PRIMARY KEY,
    content TEXT,
    metadata JSONB,
    embedding VECTOR(1536)
    );

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE vector_store (
                              id UUID PRIMARY KEY,
                              content TEXT,
                              metadata JSONB,
                              embedding VECTOR(3072)
);

CREATE TABLE IF NOT EXISTS spring_ai_chat_memory (
                                                     id BIGSERIAL PRIMARY KEY,
                                                     conversation_id VARCHAR(36),
    content TEXT,
    type VARCHAR(10),
    created_at TIMESTAMP DEFAULT NOW()
    );

CREATE TABLE chat_room (
                            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            title       VARCHAR(255),
                            user_id     BIGINT       NOT NULL,
                            created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT fk_chatroom_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE chat_message (
                               id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               content     TEXT         NOT NULL,
                               sender      VARCHAR(50)  NOT NULL,
                               ai_payload  TEXT,
                               room_id     BIGINT,
                               user_id     BIGINT       NOT NULL,
                               created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT fk_chatmessage_room FOREIGN KEY (room_id) REFERENCES chat_room(id),
                               CONSTRAINT fk_chatmessage_user FOREIGN KEY (user_id) REFERENCES users(id)
);