-- Vector store table for Spring AI PGVector (text-embedding-004 = 768 dimensions)
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS vector_store (
    id        UUID PRIMARY KEY,
    content   TEXT,
    metadata  JSONB,
    embedding VECTOR(768)
);

-- Spring AI chat memory (JDBC-based conversation memory)
CREATE TABLE IF NOT EXISTS spring_ai_chat_memory (
    id              BIGSERIAL PRIMARY KEY,
    conversation_id VARCHAR(36),
    content         TEXT,
    type            VARCHAR(10),
    created_at      TIMESTAMP DEFAULT NOW()
);

-- Chat room
CREATE TABLE IF NOT EXISTS chat_room (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255),
    user_id    BIGINT       NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chatroom_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Chat message
CREATE TABLE IF NOT EXISTS chat_message (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT         NOT NULL,
    sender     VARCHAR(50)  NOT NULL,
    ai_payload TEXT,
    room_id    BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chatmessage_room FOREIGN KEY (room_id) REFERENCES chat_room(id),
    CONSTRAINT fk_chatmessage_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Indexes for chat query paths
CREATE INDEX IF NOT EXISTS idx_chat_room_user_id ON chat_room(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_message_room_created ON chat_message(room_id, created_at);
